<nav>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <a href="http://localhost/blog/">
        <div id="name-site">
                <b>Blog les plantes</b>
        </div>
    </a>
    <div id="nav-items">
        <a href="signup.php">inscription</a><br>
        <a href="login.php"><button type="submit"><i class=" fas fa-user"></i></button></a>
    </div>
</nav>