<nav>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <a href="http://localhost/blog/">
        <div id="name-site">
           Blog les plantes
        </div>
    </a>
   
    <div id="nav-items">
        <div id="nav-links">
        <div id="nav-greetings">
       <p> Bonjour <?php echo $usernameSession['username']; ?> !</p>
</div>
        
        <a href="logout.php"><button type="submit"><i class=" fas fa-user"></i></button></a>
        </div>

    </div>
</nav>